// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsZKWSvCeJG5xwBUoGx5tvuKbiW-XKzQ',
    appId: '1:955102039435:android:915f051d26b9cdde67f38e',
    messagingSenderId: '955102039435',
    projectId: 'fmc-database-a8029',
    databaseURL: 'https://fmc-database-a8029-default-rtdb.firebaseio.com',
    storageBucket: 'fmc-database-a8029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwlgyvXDe3JLWjL7ToQVuivHjJyKJfnE',
    appId: '1:955102039435:ios:59cc647b93d6034e67f38e',
    messagingSenderId: '955102039435',
    projectId: 'fmc-database-a8029',
    databaseURL: 'https://fmc-database-a8029-default-rtdb.firebaseio.com',
    storageBucket: 'fmc-database-a8029.appspot.com',
    iosClientId: '955102039435-g2vrspvh4n8bri81b0l17our37n5sc8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrScan',
  );
}
